name: Build SunamoTwoWayDictionary

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoTwoWayDictionary
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoTwoWayDictionary/SunamoTwoWayDictionary.csproj

    - name: Build
      run: dotnet build SunamoTwoWayDictionary/SunamoTwoWayDictionary.csproj --configuration Release --no-restore

  test:
    name: Test SunamoTwoWayDictionary.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoTwoWayDictionary.Tests/SunamoTwoWayDictionary.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoTwoWayDictionary.Tests/SunamoTwoWayDictionary.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoTwoWayDictionary.Tests/SunamoTwoWayDictionary.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
